name: test-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test_compile
      run: make test_compile

  test:
    needs: test_compile
    runs-on: ubuntu-latest

    steps:
    - name: dir_lister_test
      run: make dir_lister_test
    - name: html_printer_test
      run: make html_printer_test
    - name: install_valgrind
      run: sudo apt install valgrind

  valgrind:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: valgrind
      run: make valgrind_test

  prod-compile:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: clean
      run: make clean
    - name: compile
      run: make compile
    - name: dir_lister_test
      run: make dir_lister_test
    - name: html_printer_test
      run: make html_printer_test
    - name: install_valgrind
      run: sudo apt install valgrind
    - name: valgrind
      run: make valgrind_test
